cp /Users/m/dev/solidity/test/libsolidity/astPropertyTests/forLoop/isSimpleCounterLoop_negative_cases.sol .
cp /Users/m/dev/solidity/test/libsolidity/astPropertyTests/forLoop/isSimpleCounterLoop_positive_cases.sol .
cp /Users/m/dev/solidity/test/libsolidity/smtCheckerTests/inline_assembly/assembly_1.sol .
cp /Users/m/dev/solidity/test/libsolidity/smtCheckerTests/inline_assembly/assembly_2.sol .
cp /Users/m/dev/solidity/test/libsolidity/smtCheckerTests/inline_assembly/assembly_3.sol .
cp /Users/m/dev/solidity/test/libsolidity/smtCheckerTests/inline_assembly/assembly_memory_write.sol .
cp /Users/m/dev/solidity/test/libsolidity/smtCheckerTests/inline_assembly/assembly_6.sol .
cp /Users/m/dev/solidity/test/libsolidity/smtCheckerTests/inline_assembly/assembly_4.sol .
cp /Users/m/dev/solidity/test/libsolidity/smtCheckerTests/inline_assembly/assembly_5.sol .
cp /Users/m/dev/solidity/test/libsolidity/smtCheckerTests/inline_assembly/assembly_local_storage_pointer.sol .
cp /Users/m/dev/solidity/test/libsolidity/smtCheckerTests/inline_assembly/empty.sol .
cp /Users/m/dev/solidity/test/libsolidity/smtCheckerTests/inline_assembly/assembly_local_storage_access_inside_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/smtCheckerTests/inline_assembly/local_var.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/constructor/callvalue_check.sol .
cp /Users/m/dev/solidity/test/libsolidity/ASTJSON/yul_hex_literal.sol .
cp /Users/m/dev/solidity/test/libsolidity/ASTJSON/assembly/loop.sol .
cp /Users/m/dev/solidity/test/libsolidity/ASTJSON/assembly/leave.sol .
cp /Users/m/dev/solidity/test/libsolidity/ASTJSON/assembly/stringlit.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV1/dynamic_memory_copy.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/leave_outside_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/leave_inside_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV1/cleanup/cleanup.sol .
cp /Users/m/dev/solidity/test/libsolidity/ASTJSON/assembly/call.sol .
cp /Users/m/dev/solidity/test/libsolidity/smtCheckerTests/unsupported/assembly_1.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV1/enums.sol .
cp /Users/m/dev/solidity/test/libsolidity/ASTJSON/assembly/nested_functions.sol .
cp /Users/m/dev/solidity/test/libsolidity/ASTJSON/assembly/switch.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV1/return_dynamic_types_cross_call_out_of_range_1.sol .
cp /Users/m/dev/solidity/test/libsolidity/ASTJSON/assembly/function.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/localStorageVariables/assembly/reverting_function_declaration.sol .
cp /Users/m/dev/solidity/test/libsolidity/ASTJSON/assembly/var_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/localStorageVariables/assembly/if_declaration_err.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/localStorageVariables/assembly/switch_declaration_err.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/localStorageVariables/assembly/for_declaration_err.sol .
cp /Users/m/dev/solidity/test/libsolidity/ASTJSON/assembly/empty_block.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/localStorageVariables/assembly/switch_declaration_fine.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/localStorageVariables/assembly/returning_function_declaration.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/localStorageVariables/assembly/stub_declaration.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/localStorageVariables/assembly/for_declaration_fine.sol .
cp /Users/m/dev/solidity/test/libsolidity/ASTJSON/assembly/slot_offset.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV1/return_dynamic_types_cross_call_out_of_range_2.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/dirty_calldata_bytes.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/uninitializedAccess/assembly.sol .
cp /Users/m/dev/solidity/test/libsolidity/ASTJSON/assembly/switch_default.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_for.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/uninitializedFunctionPointer/uninitialized_internal_storage_function_via_yul.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/optimize_memory_store_multi_block.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/uninitializedFunctionPointer/uninitialized_internal_storage_function_legacy.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/slot_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_write_to_stack.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_storage_access_inside_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/difficulty.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/events/event.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_read_and_write_stack.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_storage_access_local_var.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/slot_access_via_mapping_pointer.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/leave.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/unreachableCode/assembly/for_break.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/calldata_offset_read_write.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/unreachableCode/assembly/for_continue.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/truefalse.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/optimize_memory_store_multi_block_bugreport.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/calldata_length_read.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/basefee_berlin_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/dirty_memory_int32.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/unreachableCode/assembly/double_revert.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/shadowing_local_function_opcode.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_if.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/unreachableCode/assembly/revert.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/keccak_yul_optimization.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_function_call2.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/dirty_memory_static_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/keccak256_optimization.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/keccak256_assembly.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/unreachableCode/assembly/return.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/keccak256_optimizer_cache_bug.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/calldata_assign_from_nowhere.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_memory_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/constants/asm_constant_file_level.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/external_function_pointer_address.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/return_and_convert.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/constant_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/calldata_array_assign_dynamic.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inlineasm_empty_let.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/constants/asm_address_constant_regression.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/prevrandao.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/keccak_optimization_bug_string.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_storage_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/calldata_array_assign_static.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/external_function_pointer_address_assignment.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/external_function_pointer_selector_assignment.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_for2.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_function_call_assignment.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/calldata_struct_assign_and_return.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/chainid.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_storage_access_via_pointer.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/function_name_clash.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_switch.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/calldata_array_read.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_function_call.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/selfbalance.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/calldata_struct_assign.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_recursion.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/conversion/implicit_cast_assignment.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/conversion/implicit_cast_function_call.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_in_modifiers.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/external_function_pointer_selector.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/keccak256_optimizer_bug_different_memory_location.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/conversion/implicit_cast_local_assignment.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/constant_access_referencing.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/storageReturn/assembly_err.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/inline_assembly_embedded_function_call.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/calldata_assign.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/calldata_offset_read.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/unary_operations.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/inlineAssembly/external_identifier_access_shadowing.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/storageReturn/assembly/reverting_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/optimizer/shift_bytes.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/cleanup/checked_arithmetic.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/cleanup/comparison.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/storageReturn/assembly/stub.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/storageReturn/assembly/switch_fine.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/storageReturn/assembly/switch_err.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/storage/dirty_storage_static_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/storageReturn/assembly/for_err.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/storage/mappings.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/storage/dirty_storage_struct.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/storageReturn/assembly/returning_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/storage/dirty_storage_bytes_long.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/storageReturn/assembly/switch_only_default_warn.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/storage/dirty_storage_bytes.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/shifts/shift_right_garbled_signed_v1.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/storageReturn/assembly/if_err.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/storage/dirty_storage_dynamic_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/controlFlow/storageReturn/assembly/for_fine.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/shifts/shift_right_garbled_signed_v2.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/shifts/bitwise_shifting_constants_constantinople.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/dirty_memory_uint32.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/simple_inline_asm.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/shifts/shifts.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/dirty_memory_struct.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/various_inline_asm.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/shifts/shift_cleanup_garbled.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/empty_return_corrupted_free_memory_pointer.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/shifts/shift_bytes_cleanup.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/memory_struct_allow.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/shifts/bitwise_shifting_constantinople.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/shifts/shift_bytes_cleanup_viaYul.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/shifts/bitwise_shifting_constantinople_combined.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/shifts/shift_right_garbled_v1.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/shifts/shift_right_garbled_v2.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/msg_sender.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/immutable/immutable_signed.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/dirty_memory_dynamic_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/viaYul/dirty_calldata_struct.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/calldata/calldata_struct_cleaning.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/userDefined/operator_parameter_cleanup.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/userDefined/operator_parameter_and_return_cleanup_between_calls.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/userDefined/operator_making_pure_external_call.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/userDefined/operator_return_parameter_cleanup.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/shanghai/evmone_support.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/operators/userDefined/operator_making_view_external_call.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/ecrecover/failing_ecrecover_invalid_input_asm.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/externalContracts/_prbmath/PRBMathCommon.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/externalContracts/_prbmath/PRBMathUD60x18.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/externalContracts/_prbmath/PRBMathSD59x18.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/externalContracts/_base64/base64_inline_asm.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/externalContracts/_stringutils/stringutils.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/delete/delete_bytes_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/delete/delete_memory_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/delete/delete_storage_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/delete/delete_storage_array_packed.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/externalContracts/snark.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/copying/dirty_memory_bytes_to_storage_copy.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/literals/hex_string_with_non_printable_characters.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/pop/byte_array_pop_long_storage_empty_garbage_ref.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/copying/array_copy_clear_storage.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/bytes_to_fixed_bytes_cleanup.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/array_storage_index_zeroed_test.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/invalid_encoding_for_storage_byte_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/copying/array_copy_cleanup_uint128.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/copying/empty_bytes_copy.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/copying/array_copy_cleanup_uint40.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/copying/copy_byte_array_to_storage.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/dirty_calldata_dynamic_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/byte_array_storage_layout.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/copying/dirty_memory_bytes_to_storage_copy_ir.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/array/copying/array_copy_clear_storage_packed.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/functionTypes/comparison_operator_for_external_function_cleans_dirty_bits.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/tryCatch/malformed_panic_3.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/tryCatch/malformed_panic_2.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/state/block_basefee.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/tryCatch/malformed_panic_4.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/byte_array_to_storage_cleanup.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/tryCatch/invalid_error_encoding.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/tryCatch/malformed_panic.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/deployedCodeExclusion/module_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/tryCatch/malformed_error.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/deployedCodeExclusion/subassembly_deduplication.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/revertStrings/invalid_abi_decoding_memory_v1.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/deployedCodeExclusion/library_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/deployedCodeExclusion/virtual_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/deployedCodeExclusion/static_base_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/deployedCodeExclusion/bound_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/deployedCodeExclusion/super_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/exponentiation/signed_base.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/exponentiation/small_exp.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/cleanup/cleanup_address_types_shortening.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening_OldCodeGen.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/enums/invalid_enum_logged.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/asmForLoop/for_loop_nested.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/cleanup/indexed_log_topic_during_explicit_downcast.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/asmForLoop/for_loop_break.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/asmForLoop/for_loop_continue.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/cleanup/cleanup_bytes_types_shortening_newCodeGen.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/cleanup/indexed_log_topic_during_explicit_downcast_during_emissions.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/libraries/library_function_selectors.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/variables/storing_invalid_boolean.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/libraries/library_return_struct_with_mapping.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/libraries/library_delegatecall_guard_view_not_needed.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/functionCall/calling_uninitialized_function_through_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/libraries/library_function_selectors_struct.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/memoryManagement/return_variable.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/libraries/library_delegatecall_guard_pure.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/memoryManagement/static_memory_array_allocation.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/memoryManagement/assembly_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/functionCall/calling_uninitialized_function_in_detail.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/memoryManagement/struct_allocation.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/unused_store_storage_removal_bug.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/libraries/library_delegatecall_guard_view_needed.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/structs/struct_delete_storage_with_arrays_small.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/structs/struct_delete_storage_small.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/functionCall/return_size_shorter_than_expected_evm_version_after_homestead.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/parsing/assembly_evmasm_type.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/various/codehash_assembly.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/cleanup/dynamic_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/parsing/assembly_invalid_type.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/cleanup/reencoded_calldata_string.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/cleanup/static_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/cleanup/uintx.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/expressions/bit_operators.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/cleanup/function.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/functionCall/return_size_bigger_than_expected.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/various/byte_optimization_bug.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/various/code_access_runtime.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/various/code_access_create.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/cleanup/cleanup.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/various/iszero_bnot_correct.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/cleanup/address.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/various/codebalance_assembly.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/cleanup/bytesx.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/cleanup/intx.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/various/address_code_complex.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/functionCall/return_size_shorter_than_expected.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/cleanup/bool.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/cleanup/simple_struct.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/various/many_subassemblies.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/various/create_random.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/various/code_access_padding.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/struct/struct_validation.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/various/code_access_content.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/abiEncoderV2/enums.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/structs/struct_delete_storage_with_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/various/code_length.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/structs/recursive_struct_2.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/structs/struct_delete_storage_nested_small.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/immutable/assembly.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/nameAndTypeResolution/shadowsBuiltin/illegal_names_assembly_functions.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/reverts/invalid_enum_as_external_ret.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/nameAndTypeResolution/shadowsBuiltin/illegal_names_assembly_identifier.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/reverts/invalid_enum_as_external_arg.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/reverts/invalid_instruction.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/reverts/revert_return_area.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/reverts/revert.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/reverts/invalid_enum_compared.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/reverts/invalid_enum_stored.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/unmarked_with_memory_assignment.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/unmarked_with_memory_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/userDefinedValueType/immutable_signed.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/dialectString/free_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/callvalue_payable_assembly_fallback.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/dialectString/constructor_safe_deploy_unsafe.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/dialectString/constructor_unsafe_deploy_safe.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/userDefinedValueType/assembly_access_bytes2_abicoder_v1.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/dialectString/safe_and_unmarked_empty.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure_london.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/dialectString/safe_and_unmarked_unsafe.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/dialectString/multiple_contracts.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/unmarked_but_no_memory_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure_constantinople.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/assembly.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/comment/free_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_view_london.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/comment/constructor_safe_deploy_unsafe.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure_pre_paris.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/comment/constructor_unsafe_deploy_safe.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/metaTypes/runtimeCodeWarningAssembly.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/callvalue_payable_assembly_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/comment/safe_and_unmarked_empty.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/basefee_not_pure.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure_istanbul.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/comment/safe_and_unmarked_unsafe.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/callvalue_nonpayable_assembly_function_internal.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/comment/multi_annotation.sol .
cp /Users/m/dev/solidity/test/libsolidity/memoryGuardTests/comment/multiple_contracts.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/userDefinedValueType/parameter.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/userDefinedValueType/assembly_access_bytes2_abicoder_v2.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_london.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/difficulty_nobuiltin_post_paris.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/userDefinedValueType/storage_signed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/immutables.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/types/var_decl_val_mismatch.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/callvalue_nonpayable_assembly_fallback.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/basefee_reserved_london.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/circular_constant_access_module_err.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/storage_reference_old_shadow.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/use_msize_with_optimizer.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/userDefinedValueType/cleanup_abicoderv1.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/hex_switch_case.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_view.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/constant_computation.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure_byzantium.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/function_call_not_found.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/storage_reference_on_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/callvalue_payable_assembly_function_modifier.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/prevrandao_allowed_function_pre_paris.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/callvalue_nonpayable_assembly_function_modifier.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/assembly_chainid_not_pure.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/userDefinedValueType/dirty_slot.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assignment_from_contract.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_view.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/storage_reference_assignment_statevar.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/constant_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/assembly_istanbul.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/prevrandao_builtin_post_paris.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/callvalue_nonpayable_assembly_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assignment_from_library.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_disallowed_pure_paris.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/userDefinedValueType/cleanup.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/assembly_constantinople.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/userDefinedValueType/storage_layout.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/userDefinedValueType/dirty_uint8_read.sol .
cp /Users/m/dev/solidity/test/libsolidity/semanticTests/userDefinedValueType/storage_layout_struct.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/types/magic_block_london.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/returndatasize_as_variable_pre_byzantium.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/leave.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/viewPureChecker/inline_assembly_instructions_allowed_pure.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/storage_slot_assign.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/circular_module_access_err.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assignment_location.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/difficulty_builtin_pre_paris.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/evm_byzantium_on_homestead.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/evm_istanbul_on_petersburg.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/types/magic_block_paris.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assignment_from_super.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/returndatasize_as_variable_post_byzantium.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/circular_constant_access_err.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/function_call_invalid_argument_count.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/natspec_multi.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/constant_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assembly_dialect_invalid_options.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/solidity_keywords.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/storage_reference_empty_slot.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assignment_from_functiontype2.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/memory_safe_in_dialect_string.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/storage_reference_on_memory.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assembly_dialect_leading_space.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/extcodehash_as_variable_post_constantinople.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assignment_to_special.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/linkersymbol_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/evm_constantinople.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/linkersymbol_builtin.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assignment_from_opcode_like.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/returndatasize_as_variable_read_post_byzantium.sol.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/hex_assignment.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/storage_reference_old.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/function_without_call.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assignment_to_function_pointer.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/create2_as_variable_pre_istanbul.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assembly_invalid_options.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/leave_invalid.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/evm_istanbul.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/memory_safe_dialect_string_and_comment.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/reserved_identifiers_byzantium.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/evm_byzantium.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/const_forward_reference.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/external_identifier_access_shadowing.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/hex_expression.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/const_from_non_const.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/push0_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/constant_bytes_ref.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assembly_dialect_duplicate_option.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/jump_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/identifier_starting_with_dot.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/evm_constantinople_on_byzantium.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/difficulty_disallowed_function_pre_paris.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/string_literal_switch_case.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/difficulty_reserved_post_paris.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/extcodehash_as_variable_pre_constantinople.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/prevrandao_nobuitin_pre_paris.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/period_in_identifer.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/returndatasize_as_variable_call_post_byzantium.sol.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assembly_empty_option_list.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/function_call_to_variable.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/in_modifier.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assembly_duplicate_option.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assignment_from_functiontype.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/storage_reference_empty_offset.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/overloaded_reference.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/function_definition_whitespace.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/storage_reference_fine.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/use_msize_without_optimizer.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assignment_from_functiontype3.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/reserved_identifiers_constantinople.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/storage_variable_access_out_of_functions.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assembly_empty_option_list_dialect.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/storage_reference_assignment.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/verbatim_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/shadowing/local_variable.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assembly_flags_delimiter.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/assignment_to_opcode_like.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/reserved_identifiers.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/dot_in_fun_param.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/shadowing/contract.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/no_unused_variable_warning.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/two_stack_slot_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/shadowing/local_function_by_opcode.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/local_variable_access_out_of_functions.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/invalid_number.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/shadowing/state_variable_by_opcode.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/shadowing/global_function_by_opcode.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/empty_fun_arg_beginning.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/shadowing/argument.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/shadowing/constant.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/two_stack_slots.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/shadowing/name_clash_in_import.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/dot_in_vardecl.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/shadowing/variable_by_opcode.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/push_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/whitespace_in_multiple_assignment.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/shadowing/function.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/shadowing/no_name_clash_in_import.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/calldata_slot.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/shadowing/qualified_names.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/constant_variable_via_offset.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/internal_function_pointer_address.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/whitespace_in_assignment.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/pc_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/storage_nonslot.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/storage_assignment.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/illegal_names.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/internal_function_pointer_selector.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/dup_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/const_from_this.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/nested_function_local_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/jumpdest_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/constant_length_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/label_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid_natspec.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/unbalanced_two_stack_load.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/function_definition.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/assign_to_instruction.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/constant_ref.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/natspec_multi_swallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/missing_variable_in_assign.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/literals_on_stack_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/constant_access_non_initialized.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/assignment_to_function.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/create2_as_variable_post_istanbul.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/calldata_variables.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/calldata_array_offset.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/constant_access.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/unbalanced_positive_stack.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/natspec_memory_safe.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/const_forward_reference.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/local_variable_access_out_of_functions_storage_ptr.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/unbalanced_negative_stack.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/swap_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/calldata_array.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/storage_reference.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/multiple_assign_to_instruction.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/jumpi_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/empty_fun_arg_middle.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/constant_assignment.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/leave_items_on_stack.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/dot_in_multi_vardecl.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/empty_function_name.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/external_function_pointer_offset.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/prevrandao_disallowed_function_post_paris.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/variable_declaration_suffix_offset.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/missing_variable.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/dot_in_fundecl.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/empty_fun_arg_end.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/storage_assignment_in_modifier.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/inlineAssembly/invalid/bare_instructions_disallowed.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/literals/hex_string_duplicate_underscore_yul.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/literals/hex_string_invalid_characters_yul.sol .
cp /Users/m/dev/solidity/test/libsolidity/syntaxTests/string/hex_as_identifier.sol .
